### PR TITLE
plugins: Text and whitespace fixes

### PR DESCRIPTION
**Pull request by dperpeet**
If/Then sentences should now uniformly begin with a capital letter.
Also minor python whitespace cleanup.

The Cockpit ui plugin for setroubleshoot (wip: https://github.com/cockpit-project/cockpit/pull/3962/) would look better if the Messages started with capitalized letters.

Is there a way to preserve translations? I don't want to break all the work that's been done for minor changes.

### CODE REVIEW

**Comment by bachradsusi** [comment]
Thanks for the patch.
 
`if_text` is always wrapped with `_("If ")` therefore *if* sentences should not start with a capital letter. 

I would rather have two patches here, one for  the text changes and other for  whitespace fixes.

Please use fedora-selinux:python3 branch as a development base. master is considered as legacy python2 while all new things goes to python3. We need to document it and probably change the structure to be more  consistent.

As for the translations, we use fedora.zanata.org. It should be feasible to merge old translations with new strings. However I need to check it and find out how.

**Comment by dperpeet** [comment]
Interesting.

> if_text is always wrapped with _("If ") therefore if sentences should not start with a capital letter.
Via dbus api you deliver the text including the "If ", correct? Am I correct to assume that the "if" text in plugins should start with lower case? Or is that done programmatically?

What about conditions for 'then' and 'do'? The 'do' part seems especially heterogeneous.

I will change this pr and split the modifications.

**Comment by bachradsusi** [comment]
"If " is added in browser and using DBUS api as well.

We need to change strings to already contain "If " on the beginning since sometime is simply not possible to put "If" in other language to the beginning of a sentence.

**Comment by bachradsusi** [comment]
Note: it will be fixed by https://github.com/bachradsusi/setroubleshoot/commits/rework-plugin-strings . However I need to be synchronized with translation team. See bugs https://bugzilla.redhat.com/show_bug.cgi?id=1322734 and https://bugzilla.redhat.com/show_bug.cgi?id=1210243

**Comment by bachradsusi** [comment]
The change described in https://fedora.zanata.org/project/view/setroubleshoot?dswid=4690 is now applied in master branch - https://github.com/fedora-selinux/setroubleshoot/commit/98c2ad7c16be9b79f880964b3ccfbfbc5bb4ed58

**Pull request closed without merging**
