### PR TITLE
framework: Add man page for seapplet

### PR DESCRIPTION
**Pull request by vmojzis**

### CODE REVIEW

**Comment by bachradsusi** [comment]
It looks good. Thanks.

The only comment is that according to `man man`, the section number 8 is for *8   System administration commands (usually only for root)*. `seapplet` would be rather *1   Executable programs or shell commands*

**Comment by bachradsusi** [comment]
You need to update `doc/Makefile.am` as well:

```
--- a/framework/doc/Makefile.am
+++ b/framework/doc/Makefile.am
@@ -9,6 +9,7 @@ man_MANS =                                      \
+       seapplet.1                              \
        sealert.8                               \
        setroubleshootd.8                       \
        sedispatch.8                            \
        $(NULL)
 
 pkgdoc_DATA = $(DOC_FILES)
```

**Comment by bachradsusi** [comment]
It looks like it's already merged - https://github.com/fedora-selinux/setroubleshoot/commit/f20d2c0d138c6f9c7cf9395eae2e3644ce48cccf . Am I right?

**Comment by vmojzis** [comment]
Yes, thanks.

**Pull request closed without merging**
